name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Project
        run: cargo build --release

      - name: echo1
        run: echo "Value of MY_VARIABLE is ${{ secrets.CARGO_TOKEN }}"

      - name: echo2
        run: echo "${CARGO_TOKEN}"
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}

      - name: echo3
        run: echo "$CARGO_TOKEN"
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}


      - name: Publish Crate
        run: cargo publish --token ${CARGO_TOKEN}
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
