name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Project
        run: cargo build --release

      - name: Test Project
        run: cargo test --verbose

      - name: Publish Crate
        run: cargo publish
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
